### ISSUE TITLE
to be removed  or simplified (subset data)

### ISSUE THREAD

**Issue by caballero** [maxplanck-ie/Rintro#37]
https://github.com/maxplanck-ie/Rintro/blob/54b0f0788899881e16e63ac780daae6539777e3b/rmd/02_HighDimData.Rmd#L90C1-L100C7

subset complexity

**Comment by thomasmanke** [comment]
will keep this, as it links to a practical task, illustrates index by Truth value, and hints at future concept simplifications with dplyr...
