### ISSUE TITLE
to be removed (no all vs all correlations)

### ISSUE THREAD

**Issue by caballero** [maxplanck-ie/Rintro#41]
https://github.com/maxplanck-ie/Rintro/blob/54b0f0788899881e16e63ac780daae6539777e3b/rmd/04_DataDescriptions.Rmd#L101C1-L115C4

https://github.com/maxplanck-ie/Rintro/blob/54b0f0788899881e16e63ac780daae6539777e3b/rmd/05_DataModels.Rmd#L17C1-L30C1

**Comment by caballero** [comment]
removed from 2023.03

**Comment by thomasmanke** [comment]
I keep the first - but condensed the second.
