### ISSUE TITLE
reduce and convert to example tasks

### ISSUE THREAD

**Issue by caballero** [maxplanck-ie/Rintro#45]
https://github.com/maxplanck-ie/Rintro/blob/54b0f0788899881e16e63ac780daae6539777e3b/rmd/05_DataModels.Rmd#L162C1-L174C4

**Comment by thomasmanke** [comment]
I would also leave this. I did not appreciate that this example is not so much about the fancy fits, but rather an illustration of the residual error decreasing as we increase number of features - i think this is an important point. Will keep unless I find an easier way to illustrate this point. Any ideas?

**Comment by thomasmanke** [comment]
added plot to illustrate reduction in residual error for more complex models
