### ISSUE TITLE
to be removed (start with heatmaps)

### ISSUE THREAD

**Issue by caballero** [maxplanck-ie/Rintro#46]
https://github.com/maxplanck-ie/Rintro/blob/54b0f0788899881e16e63ac780daae6539777e3b/rmd/06_DataVisualization.Rmd#L19C1-L30C4

**Comment by thomasmanke** [comment]
Actually, I would keep the short introduction to scaling. The following code (pheatmap) was already much simplified - and it feels like a much shorter intro now. I'm fine with it as is.
